emprunts = [
    {'titre': 'Le Comte de Monte-Cristo',    'adherent': 'Alice Moreau',   'duree': 21, 'note': 5},
    {'titre': 'Les Misérables',              'adherent': 'Bruno Leroy',    'duree': 28, 'note': 4},
    {'titre': 'Germinal',                    'adherent': 'Camille Dupuis', 'duree': 14, 'note': 3},
    {'titre': "L'Étranger",                  'adherent': 'Alice Moreau',   'duree':  7, 'note': 5},
    {'titre': 'Le Petit Prince',             'adherent': 'David Petit',    'duree':  5, 'note': 5},
    {'titre': 'Madame Bovary',               'adherent': 'Elise Faure',    'duree': 18, 'note': 4},
    {'titre': 'Les Fleurs du mal',           'adherent': 'Bruno Leroy',    'duree': 12, 'note': 2},
    {'titre': 'Voyage au bout de la nuit',   'adherent': 'Camille Dupuis', 'duree': 22, 'note': 3},
    {'titre': 'La Modification',             'adherent': 'David Petit',    'duree': 16, 'note': 4},
    {'titre': 'Bonjour tristesse',           'adherent': 'Elise Faure',    'duree':  9, 'note': 5},
    {'titre': 'Le Comte de Monte-Cristo',    'adherent': 'Elise Faure',    'duree': 30, 'note': 4},
    {'titre': 'Les Misérables',              'adherent': 'Alice Moreau',   'duree': 35, 'note': 5},
    {'titre': 'Germinal',                    'adherent': 'David Petit',    'duree':  8, 'note': 4},
    {'titre': "L'Étranger",                  'adherent': 'Bruno Leroy',    'duree':  6, 'note': 3},
    {'titre': 'Le Petit Prince',             'adherent': 'Camille Dupuis', 'duree':  4, 'note': 5},
    {'titre': 'Madame Bovary',               'adherent': 'Alice Moreau',   'duree': 20, 'note': 2},
    {'titre': 'Les Fleurs du mal',           'adherent': 'Elise Faure',    'duree': 11, 'note': 3},
    {'titre': 'Voyage au bout de la nuit',   'adherent': 'Bruno Leroy',    'duree': 25, 'note': 4},
    {'titre': 'La Modification',             'adherent': 'Alice Moreau',   'duree': 13, 'note': 3},
    {'titre': 'Bonjour tristesse',           'adherent': 'David Petit',    'duree':  7, 'note': 4},
    {'titre': 'Le Comte de Monte-Cristo',    'adherent': 'Bruno Leroy',    'duree': 42, 'note': 5},
    {'titre': 'Les Misérables',              'adherent': 'Camille Dupuis', 'duree': 40, 'note': 4},
    {'titre': 'Germinal',                    'adherent': 'Elise Faure',    'duree': 17, 'note': 5},
    {'titre': "L'Étranger",                  'adherent': 'David Petit',    'duree':  5, 'note': 4},
    {'titre': 'Madame Bovary',               'adherent': 'Camille Dupuis', 'duree': 19, 'note': 3},
]
